package dal

import (
	"database/sql"
	"fmt"
	"mgmt-server/model"
)

type ChatRoomDAL struct {
	db *sql.DB
}

func NewChatRoomDAL(db *sql.DB) *ChatRoomDAL {
	return &ChatRoomDAL{
		db: db,
	}
}

func (c *ChatRoomDAL) CreateChatRoom(chatRoom model.ChatRoom) (*model.ChatRoom, error) {
	query := `
		INSERT INTO chatrooms (title) VALUES ($1)
		RETURNING id
	`

	var autoGeneratedId int64
	err := c.db.QueryRow(query, chatRoom.Title).Scan(&autoGeneratedId)
	if err != nil {
		return nil, fmt.Errorf("failed to insert chatroom: %+v", chatRoom)
	}

	return &model.ChatRoom{
		ID:    autoGeneratedId,
		Title: chatRoom.Title,
	}, nil
}
