package dal

import (
	"database/sql"
	"fmt"
	"mgmt-server/model"
)

type UserDAL struct {
	db *sql.DB
}

func NewUserDAL(db *sql.DB) *UserDAL {
	return &UserDAL{
		db: db,
	}
}

func (u *UserDAL) CreateUser(user model.User) (*model.User, error) {
	query := `
		INSERT INTO users (email, password) VALUES ($1, $2)
		RETURNING id
	`

	var autoGeneratedId int64
	err := u.db.QueryRow(query, user.Email, user.Password).Scan(&autoGeneratedId)
	if err != nil {
		return nil, fmt.Errorf("failed to insert user: %+v", user)
	}

	return &model.User{
		ID:       autoGeneratedId,
		Email:    user.Email,
		Password: user.Password,
	}, nil
}
